#
# CDDL HEADER START
#
# The contents of this file are subject to the terms of the
# Common Development and Distribution License (the "License").
# You may not use this file except in compliance with the License.
#
# You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
# or http://www.opensolaris.org/os/licensing.
# See the License for the specific language governing permissions
# and limitations under the License.
#
# When distributing Covered Code, include this CDDL HEADER in each
# file and include the License file at usr/src/OPENSOLARIS.LICENSE.
# If applicable, add the following below this CDDL HEADER, with the
# fields enclosed by brackets "[]" replaced with your own identifying
# information: Portions Copyright [yyyy] [name of copyright owner]
#
# CDDL HEADER END
#

#
# Copyright 2007 Sun Microsystems, Inc.  All rights reserved.
# Use is subject to license terms.
#

#
# The primary Makefile for making the test purpose binaries either ksh
# or c code.  This Makefile includes the configuration bits to make sure
# the libraries are setup correctly to point to the correct libs.
#

include $(TET_SUITE_ROOT)/scm/Targetdirs

.KEEP_STATE:

#
# Set the variables for the correct configuration of the test
# suite.
#
BIN_DIR			= ../../bin

OBJDIR			= obj_dir

COMMON_TESTLIB		= -lCommonTest
COMMON_SHLIB_TESTLIB	= -lCommonTest_s
COMMON_SCRIPT_TESTLIB	= -lCommonTest_script
                          
DISTLIBS		= -lsocket -lnsl

#
# Process the variables set in the test level Makefiles to the 
# correct values to create the correct objects for execution
#
SRCS		= $(TESTFILES:%=%.c)
OBJS		= $(TESTFILES:%=$(OBJDIR)/%.o) 
SRCS_KSH	= $(TARGET_KSH:%=%.ksh)
SRCS_PERL	= $(TARGET_PERL:%=%.pl)
FILES_KSH	= $(TARGET_KSH)
FILES_PERL	= $(TARGET_PERL)

#
# Set the libs settings to the correct paths to include the correct
# libraries into the tests
#
_LIBS_	=  -L$(COMMON_LIB) -L$(CTI_LIB) $(DISTLIBS) $(COMMON_TESTLIB) \
	$(COMMON_SCRIPT_TESTLIB)
LIBS	= $(_LIBS_)

#
# The socket and nsl libs are required for distributed testing
#
_SYSLIBS_	= -lsocket -lnsl

#
# Set the correct include paths so the compilation can find the include
# files that are included in the test cases.
#
CFLAGS		= -I$(TET_INC) -I$(COMMON_INC) -I$(CTI_INC)
LINTFLAGS	= -I$(TET_INC) -I$(COMMON_INC)

#
# Set the dependency directories so that these directories are built
# before any of the tests so the objects and files can be linked and/or
# included into the tests
#
TARGET_DEPENDENCIES = $(TET_SUITE_ROOT)/scm/src

include $(CTI_ROOT)/Makefiles/Makefile.tests

all : $(TARGET_DEPENDENCIES) $(SRC) $(FILES_KSH) $(FILES_PERL)

$(SRC) : $(PLAT_DIR) $(OBJS)
	@$(RM) $@
	$(CC) $(TET_OBJS) $(OBJS) -o $@ $(LIBS) $(TET_API_LIB) $(SYSLIBS) $(SYSLIBS_ADD)

$(OBJS) : $(OBJDIR) $(SRCS)
	@$(RM) $@
	$(CC) $(CFLAGS) $(CFLAGS_ADD) $(@:$(OBJDIR)/%.o=%.c) -o $@ -c

$(TARGET_DEPENDENCIES) : FRC
	@cd $(TARGET_DEPENDENCIES); $(MAKE) all

clean :
	@$(RM) -r $(SRC) $(TARGET) $(TARGET_SCRIPT) $(TARGET_KSH) $(FILES_KSH) $(TARGET_PERL) $(FILES_PERL) *.o
	@$(RM) -r $(OBJDIR)

clobber : clean
	@$(RM) core *% tet_captured

lint :
	@$(LINT.c) -errfmt=simple -errhdr=%user -ux $(LINTFLAGS) $(CFLAGS_ADD) $(SRCS)

$(OBJDIR) : 
	@mkdir -p -m 0777  $(OBJDIR)

FRC :

